//
// Generated file, do not edit! Created by nedtool 4.6 from P_pdu.msg.
//

#ifndef _P_PDU_M_H_
#define _P_PDU_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>P_pdu.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet P_pdu
 * {
 *     int id;
 *     int type;
 *     char a;
 * }
 * </pre>
 */
class P_pdu : public ::cPacket
{
  protected:
    int id_var;
    int type_var;
    char a_var;

  private:
    void copy(const P_pdu& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const P_pdu&);

  public:
    P_pdu(const char *name=NULL, int kind=0);
    P_pdu(const P_pdu& other);
    virtual ~P_pdu();
    P_pdu& operator=(const P_pdu& other);
    virtual P_pdu *dup() const {return new P_pdu(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id);
    virtual int getType() const;
    virtual void setType(int type);
    virtual char getA() const;
    virtual void setA(char a);
};

inline void doPacking(cCommBuffer *b, P_pdu& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, P_pdu& obj) {obj.parsimUnpack(b);}


#endif // ifndef _P_PDU_M_H_

