//
// Generated file, do not edit! Created by nedtool 4.6 from p.msg.
//

#ifndef _P_M_H_
#define _P_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>p.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet P
 * {
 *     int id;
 *     int type;
 * 
 * }
 * </pre>
 */
class P : public ::cPacket
{
  protected:
    int id_var;
    int type_var;

  private:
    void copy(const P& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const P&);

  public:
    P(const char *name=NULL, int kind=0);
    P(const P& other);
    virtual ~P();
    P& operator=(const P& other);
    virtual P *dup() const {return new P(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id);
    virtual int getType() const;
    virtual void setType(int type);
};

inline void doPacking(cCommBuffer *b, P& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, P& obj) {obj.parsimUnpack(b);}


#endif // ifndef _P_M_H_

